version: "1"
services:
  # Collector
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
      - ./metrics.json:/metrics.json
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"